In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [3]:
filepath = os.path.join('..','data','Internship_Selection_Dataset.csv')
df = pd.read_csv(filepath)

df.head(8)

,student_id,CGPA,skills_score,projects_count,internships_done,communication_score,aptitude_score,coding_test_score,resume_score,extracurricular,...,hackathons_participated,certifications_count,linkedin_activity_score,github_score,soft_skills_score,interview_score,consistency_score,backlogs,placement_training,selected
0,1,6.87,7,0,0,4,3,2,7,Yes,...,0,7,5,9,3,1,4,4,Yes,1
1,2,9.75,4,4,2,3,3,6,1,Yes,...,3,2,8,8,3,9,8,5,Yes,1
2,3,8.66,2,1,1,2,1,4,6,Yes,...,4,1,5,2,2,1,3,2,Yes,1
3,4,7.99,5,4,2,8,8,10,8,No,...,1,5,5,9,2,7,10,1,Yes,1
4,5,5.78,3,2,2,4,9,1,7,Yes,...,4,7,3,8,7,8,6,5,Yes,1
5,6,5.78,9,5,1,2,5,1,5,No,...,2,9,4,8,3,7,4,4,No,0
6,7,5.29,6,3,1,9,1,2,4,Yes,...,4,7,9,1,10,2,2,5,Yes,1
7,8,9.33,1,2,0,8,1,4,2,Yes,...,2,5,9,2,3,6,1,2,No,0

In [4]:
col = [cols for cols in df.columns if df[cols].dtype == 'O']
print(col)

['extracurricular', 'college_tier', 'placement_training']

#### In DF['extracurricular'] encoding
{
    "Yes" : 1, (6025 count)
    "No" : 0, (3975 count)
}

In [5]:
df['extracurricular'].value_counts()

extracurricular
Yes    6025
No     3975
Name: count, dtype: int64

In [6]:
df['extracurricular'] = np.where(df['extracurricular'].str.contains("Yes"),1,0)

In [7]:
col = [cols for cols in df.columns if df[cols].dtype == 'O']
print(col)

['college_tier', 'placement_training']

#### In DF['College_tier'] Encoding
{Tier 1 : 1 (3044 count), Tier 2 : 2 (4944 count), Tier 3 : 3 (2012 count)}

In [8]:
df['college_tier'].value_counts()

college_tier
Tier 2    4944
Tier 1    3044
Tier 3    2012
Name: count, dtype: int64

In [9]:
df['college_tier'] = df['college_tier'].replace("Tier 1",1)
df['college_tier'] = df['college_tier'].replace("Tier 2",2)
df['college_tier'] = df['college_tier'].replace("Tier 3",3)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_32584\1970348299.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['college_tier'] = df['college_tier'].replace("Tier 3",3)

#### In DF['placement_training'] encoding
{
    "Yes" : 1, (6876 count)
    "No" : 0, (3124 count)
}

In [10]:
df['placement_training'].value_counts()

placement_training
Yes    6876
No     3124
Name: count, dtype: int64

In [11]:
df['placement_training'] = np.where(df['placement_training'].str.contains("Yes"),1,0)

In [12]:
df.columns

Index(['student_id', 'CGPA', 'skills_score', 'projects_count',
       'internships_done', 'communication_score', 'aptitude_score',
       'coding_test_score', 'resume_score', 'extracurricular', 'college_tier',
       'hackathons_participated', 'certifications_count',
       'linkedin_activity_score', 'github_score', 'soft_skills_score',
       'interview_score', 'consistency_score', 'backlogs',
       'placement_training', 'selected'],
      dtype='object')

In [13]:
X = df.drop(columns='selected',axis=1)
y = df['selected']

print(X.columns)
print("\n",y.name)

Index(['student_id', 'CGPA', 'skills_score', 'projects_count',
       'internships_done', 'communication_score', 'aptitude_score',
       'coding_test_score', 'resume_score', 'extracurricular', 'college_tier',
       'hackathons_participated', 'certifications_count',
       'linkedin_activity_score', 'github_score', 'soft_skills_score',
       'interview_score', 'consistency_score', 'backlogs',
       'placement_training'],
      dtype='object')

 selected

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

X_train.shape , X_test.shape, y_train.shape, y_test.shape

((7500, 20), (2500, 20), (7500,), (2500,))

In [17]:
X_train.columns[:5]

Index(['student_id', 'CGPA', 'skills_score', 'projects_count',
       'internships_done'],
      dtype='object')

In [22]:
X.corr()

,student_id,CGPA,skills_score,projects_count,internships_done,communication_score,aptitude_score,coding_test_score,resume_score,extracurricular,college_tier,hackathons_participated,certifications_count,linkedin_activity_score,github_score,soft_skills_score,interview_score,consistency_score,backlogs,placement_training
student_id,1.000000,-0.011074,0.003795,-0.009880,0.008719,-0.013819,-0.001480,-0.016695,0.007719,0.020514,-0.000578,-0.020229,-0.003328,0.009745,0.005905,-0.003972,0.008018,-0.020733,-0.004385,0.013304
CGPA,-0.011074,1.000000,-0.006062,0.020954,-0.001184,-0.016028,0.006523,0.005060,0.015237,0.014067,-0.004606,0.023094,-0.004572,-0.004020,0.001991,-0.012491,-0.009563,-0.016030,-0.007938,0.004757
skills_score,0.003795,-0.006062,1.000000,-0.015557,0.004458,0.008549,-0.000724,0.000629,-0.008929,-0.002919,0.007419,-0.002213,-0.002181,-0.006207,-0.003023,-0.001780,-0.010844,-0.017833,-0.002696,-0.001560
projects_count,-0.009880,0.020954,-0.015557,1.000000,-0.006111,0.009002,0.001000,-0.024157,-0.005888,0.005903,0.036606,-0.004562,0.000183,0.014841,0.005938,-0.015759,-0.014372,-0.009751,-0.006039,0.002700
internships_done,0.008719,-0.001184,0.004458,-0.006111,1.000000,-0.002794,-0.014372,0.001159,-0.001043,0.007596,0.001665,-0.004166,0.004968,-0.013449,0.001201,-0.017324,-0.019112,0.001889,-0.002177,-0.005951
communication_score,-0.013819,-0.016028,0.008549,0.009002,-0.002794,1.000000,-0.000277,0.015921,0.027236,0.012492,0.010857,-0.000871,-0.002933,0.003010,0.012599,-0.001194,-0.013720,0.005052,-0.014419,0.002726
aptitude_score,-0.001480,0.006523,-0.000724,0.001000,-0.014372,-0.000277,1.000000,0.022558,0.014191,0.012371,0.000569,-0.004771,0.020674,0.020732,-0.007079,-0.006655,0.009420,-0.006152,-0.004821,-0.006703
coding_test_score,-0.016695,0.005060,0.000629,-0.024157,0.001159,0.015921,0.022558,1.000000,-0.003392,0.007372,-0.004724,0.010187,-0.003557,-0.017128,-0.011852,0.014098,0.012386,0.008795,0.019938,0.000296
resume_score,0.007719,0.015237,-0.008929,-0.005888,-0.001043,0.027236,0.014191,-0.003392,1.000000,0.000533,0.012876,-0.002258,0.007270,-0.004962,-0.001726,-0.015950,-0.004418,0.006551,-0.015932,0.013697
extracurricular,0.020514,0.014067,-0.002919,0.005903,0.007596,0.012492,0.012371,0.007372,0.000533,1.000000,0.001679,-0.012871,0.007939,-0.003008,-0.002867,-0.014268,-0.012993,-0.008658,0.016221,0.014201
college_tier,-0.000578,-0.004606,0.007419,0.036606,0.001665,0.010857,0.000569,-0.004724,0.012876,0.001679,1.000000,-0.005090,-0.005779,-0.000837,0.002239,-0.018223,0.006720,-0.009471,-0.001730,0.007852
hackathons_participated,-0.020229,0.023094,-0.002213,-0.004562,-0.004166,-0.000871,-0.004771,0.010187,-0.002258,-0.012871,-0.005090,1.000000,-0.022012,0.015869,-0.003275,-0.013020,-0.003518,0.001487,-0.004039,0.007371
certifications_count,-0.003328,-0.004572,-0.002181,0.000183,0.004968,-0.002933,0.020674,-0.003557,0.007270,0.007939,-0.005779,-0.022012,1.000000,-0.016677,-0.005500,0.012008,-0.001501,0.011288,-0.015336,0.003839
linkedin_activity_score,0.009745,-0.004020,-0.006207,0.014841,-0.013449,0.003010,0.020732,-0.017128,-0.004962,-0.003008,-0.000837,0.015869,-0.016677,1.000000,0.009491,-0.012295,-0.011643,-0.011064,-0.001467,0.005305
github_score,0.005905,0.001991,-0.003023,0.005938,0.001201,0.012599,-0.007079,-0.011852,-0.001726,-0.002867,0.002239,-0.003275,-0.005500,0.009491,1.000000,-0.003014,-0.005291,0.000273,0.004626,0.004948
soft_skills_score,-0.003972,-0.012491,-0.001780,-0.015759,-0.017324,-0.001194,-0.006655,0.014098,-0.015950,-0.014268,-0.018223,-0.013020,0.012008,-0.012295,-0.003014,1.000000,-0.001115,-0.008506,-0.020241,-0.000513
interview_score,0.008018,-0.009563,-0.010844,-0.014372,-0.019112,-0.013720,0.009420,0.012386,-0.004418,-0.012993,0.006720,-0.003518,-0.001501,-0.011643,-0.005291,-0.001115,1.000000,0.007232,0.012141,0.013212
consistency_score,-0.020733,-0.016030,-0.017833,-0.009751,0.001889,0.005052,-0.006152,0.008795,0.006551,-0.008658,-0.009471,0.001487,0.011288,-0.011064,0.000273,-0.008506,0.007232,1.000000,-0.012794,-0.000013
backlogs,-0.004385,-0.007938,-0.002696,-0.006039,-0.002177,-0.014419,-0.004821,0.019938,-0.015932,0.016221,-0.001730,-0.004039,-0.015336,-0.001467,0.004626,-0.020241,0.012141,-0.012794,1.000000,0.015579
placement_training,0.013304,0.004757,-0.001560,0.002700,-0.005951,0.002726,-0.006703,0.000296,0.013697,0.014201,0.007852,0.007371,0.003839,0.005305,0.004948,-0.000513,0.013212,-0.000013,0.015579,1.000000

In [26]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit on training data and transform both
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 1. Initialize the models
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
lr_model = LogisticRegression(max_iter=1000)

# 2. Train the models
rf_model.fit(X_train, y_train)
lr_model.fit(X_train_scaled, y_train)

# 3. Make predictions
rf_pred = rf_model.predict(X_test)
lr_pred = lr_model.predict(X_test_scaled)

# 4. Compare Accuracy
print(f"Random Forest Accuracy: {accuracy_score(y_test, rf_pred):.4f}")
print(f"Logistic Regression Accuracy: {accuracy_score(y_test, lr_pred):.4f}")

Random Forest Accuracy: 0.7612
Logistic Regression Accuracy: 0.7592

In [29]:
from xgboost import XGBClassifier

# Initialize and train
xgb_model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, random_state=42)
xgb_model.fit(X_train, y_train)

print(f"XGBoost Accuracy: {xgb_model.score(X_test, y_test):.4f}")

XGBoost Accuracy: 0.7520

In [32]:
!pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 6.6 MB/s eta 0:00:00
Requirement already satisfied: scipy in d:\mineprojects\intership project\intern_env\lib\site-packages (from lightgbm) (1.15.3)
Requirement already satisfied: numpy>=1.17.0 in d:\mineprojects\intership project\intern_env\lib\site-packages (from lightgbm) (2.2.6)
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

[notice] A new release of pip available: 22.2.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
from lightgbm import LGBMClassifier

lgbm_model = LGBMClassifier(n_estimators=100, learning_rate=0.05, random_state=42)
lgbm_model.fit(X_train, y_train)

print(f"LightGBM Accuracy: {lgbm_model.score(X_test, y_test):.4f}")

[LightGBM] [Info] Number of positive: 5475, number of negative: 2025
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000290 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 654
[LightGBM] [Info] Number of data points in the train set: 7500, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.730000 -> initscore=0.994623
[LightGBM] [Info] Start training from score 0.994623
LightGBM Accuracy: 0.7596

In [34]:
from sklearn.svm import SVC

# Using RBF kernel for non-linear boundaries
svm_model = SVC(kernel='rbf', probability=True, random_state=42)
svm_model.fit(X_train_scaled, y_train)

print(f"SVM Accuracy: {svm_model.score(X_test_scaled, y_test):.4f}")

SVM Accuracy: 0.7596